### ISSUE TITLE
Bug des Tridents

### ISSUE THREAD

**Issue by Nasgo007** [Achent007/MineTech#23]
**Décris le bug**
Ce bug touche particulièrement les Tridents, lorsque on le place dans l'enclume et par exemple, on veut le fusionner avec un livre de quelconque enchantement, un message apparaît dans le tchat : tu n'as pas d'item dans la main ! En plus, un des deux items disparaît, c'est soit le trident ou sois le livre.
 
**Screenshots / Vidéos **
![2019-07-09_18 37 06](https://user-images.githubusercontent.com/52711964/60907005-c831e880-a278-11e9-88ae-c99d14e0953d.png)

**Informations complémentaires**
Ce bug m'a fait disparaître un trident enchant ( canalisation , solidité 3, loyauté 3 et empalement 5 ), un autre trident non enchant, deux livres raccommodage, et un livre impulsion 3. J'aimerais me les faire rembourser à cause de ce bug

**Comment by Achent007** [comment]
Le plugin de rename Bug avec les items 1.14 Les logs sont envoyés au dev du plugin. Attente du fix de sa part.

**Comment by Achent007** [comment]
Plugin désactivé temporairement

**Comment by Achent007** [comment]
Je te rembourserai demain (j'avais pas lu le dessous)

**Comment by Achent007** [comment]
Stuff remboursé (placé dans ton inventaire)
