### ISSUE TITLE
Disparition de blocs

### ISSUE THREAD

**Issue by Oxow** [Achent007/MineTech#24]
**Décris le bug**
Voilà en ce 13/07 en début d'après-midi vers 14h plus ou moins, j'ai tué mon premier Wither et donc par la suite créer une balise. J'avais déjà posé la base de ma balise soit une base de 9x9 composé essentiellement de blocs d'or et plus ou moins une dizaine de blocs de fer. Je me suis déconnecter puis reconnecter vers 16h20. J'ai donc ainsi continué de farmer les minerais pour avoir une balise complète et en revenant à ma base soit vers 17h20, **_**tous les blocs posés avant ont disparu soit la balise et les blocs de fer/or**_** 

**Screenshots / Vidéos **
Pas de preuve concrète seulement le succès **invoquer un wither** qui prouve que normalement je dois bel et bien avoir une étoile et donc une balise 

**Informations complémentaires**
Je n'ai pas d'autres informations à ajouter à part que je ne sais pas si il y a eu un rollback pile au moment où je me suis déco ou bien si les blocs étaient toujours là quand je me suis reconnecté. ( je n'ai pas fait attention directement c'est seulement après avoir fini de farmer les deniers bloc que je m'en suis rendu compte ). 
Enfin, je précise que les blocs posés étaient dans un endroit claim au centre de ma base.

**Comment by Achent007** [comment]
Je t'ai bel et bien vu tuer ton wither, Tu as posé tes blocs durant le crash du serveur. Je t'ai donc remboursé les items (ils sont dans ton inventaire)

**Comment by Oxow** [comment]
> Je t'ai bel et bien vu tuer ton wither, Tu as posé tes blocs durant le crash du serveur. Je t'ai donc remboursé les items (ils sont dans ton inventaire)

Merci beaucoup !
