### ISSUE TITLE
Trieur d'item

### ISSUE THREAD

**Issue by PierrEauBinet** [Achent007/MineTech#28]
Lorsque je pose un droppeur en bordure  de chunk, il se casse automatiquement et se droppe au sol. Résulat : impossible de faire fonctionner un trieur qui m'a prit plusieurs jours à faire et à farmer ...

Coordonnées : à chaque limite de chunk, j'ai testé le bug à plusieurs endroits en bordure de chunk, les droppeurs dans les chunks n'ont pas de soucis

Je crois que Achent m'avait rapidement dit que c'était pour éviter les duplicateurs à items, mais personne ne s'amuse à dupliquer les items sur le serveur, et la majorité ne sait pas faire. Cet anti- duplicateur casse l'expérience de jeu des joueurs qui posent des droppeurs en bordure de chunk et voient leurs créations ( parfois laborieuses et colossales comme la mienne ) tout bonnement cassées à cause de quelque chose ( peut etre un bug tout simplement ) qui n'est la que pour empecher une duplication que personne ne fait ... j'espère que l'on pourra résoudre ce problème car mon trieur géant est hors service :/
Merci de l'attention et bon courage
PierrEauBinet.

**Comment by Achent007** [comment]
Des patchs seront appliqués demain soir

**Comment by Achent007** [comment]
Problème corrigé 😄
