### ISSUE TITLE
Bug avec le plugin de vote

### ISSUE THREAD

**Issue by SteelJim** [Achent007/MineTech#37]
**Décris le bug**
J'ai récemment changé de pseudo, et quand je vote, le message dans le chat est "**SteelJim** (mon ancien pseudo) a voté et remporte sa clef de vote". De plus, je ne reçois pas de récompense.

**Coordonées du bug**
Partout

**Screenshots / Vidéos**
https://i.imgur.com/vfmpNRQ.jpg

**Informations complémentaires**
Pas d'infos complémentaires.

**Comment by Achent007** [comment]
Bug simplement lié à ton changement de pseudo, faut éditer sur le site
