### ISSUE TITLE
Impossible de dormir

### ISSUE THREAD

**Issue by SteelJim** [Achent007/MineTech#41]
**Décris le bug**
Quand j'essaie de dormir dans un lit, le message "Spawn de lit défini !" s'affiche dans le chat, mais je ne dors pas et la nuit ne se passe pas

**Coordonées du bug**
Partout

**Screenshots / Vidéos**
https://i.imgur.com/V3jTk1Y.jpg

**Informations complémentaires**
Parfois je vois marqué dans le chat "Il faut encore 2 joueurs pour faire passer la nuit ou l'orage (1/2)" mais ce message apparaît à des moments où je n'essaie pas de dormir. Le fait que je ne puisse pas dormir a peut-être un lien avec mon grade (Sr.Admin) ou le fait que je sois OP (?)

**Comment by Achent007** [comment]
C'est une perm qu'on a avec notre op et impossible de la bloquer.
Faudra faire avec.

**Comment by Achent007** [comment]
Les op peuvent désormais dormir dans un lit !
