### ISSUE TITLE
Pas de clef vote

### ISSUE THREAD

**Issue by lixe911** [Achent007/MineTech#42]
**Décris le bug**
Vote fait après ma connexion vers 7h25 non délivrance de la clef malgré une validation sur le site.

**Informations complémentaires**
J'ai effectué plusieurs votes dans les 24 heures précédentes sans soucis.
A noter que celui là fut le premier après le redémarrage server de 4h30.
Il y a eu un redémarrage server à 2h30 environ... je ne sais pas si j'ai voté entre les deux reboots.

Désolé, pas beaucoup plus d'informations.

**Comment by Achent007** [comment]
Salut,

Je me suis connecté pour effectuer mon vote et pour moi il n'avait pas de soucis. Un autre joueur a voté à 8h33 sans problème pour lui aussi.
Je t'invite donc à réessayer de voter et si tu n'obtiens toujours aucune récompense de me contacter sur discord pour t'aider à avoir ta clef.

**Comment by lixe911** [comment]
Vote effectué avec remise de clef correctement.

Pour ce matin, je précise que c'est pas du pleurnichage genre " vous me devez une clef!" osef ^^
Je fais juste remonter le truc que j'ai eu ce matin. je surveillerais. j'essaierais de record mes votes si par hasard ça se reproduirait ( encore une fois dans le bute d'aider les devs ) , je sais même pas combien vous êtes à bosser en développement pure ( si j'avais ne serais-ce qu'une once de connaissance dans le domaine, j'essaierais volontiers d'aider ) si je peux aider dans n'importe quel autre domaine, hésite pas à demander =) .

**Comment by Achent007** [comment]
J'ai oublié de le faire et de la préciser, mais je te rends ta clef de ce matin. C'était un bug surement du site de vote ^^.
 La clef est dans ton inventaire bon jeu !
