### ISSUE TITLE
Bug connexion des joueurs

### ISSUE THREAD

**Issue by SteelJim** [Achent007/MineTech#6]
Sur le panel OMGServ on voit parqué 0 joueurs en ligne alors qu'il y en a 2

**Comment by Achent007** [comment]
API OMGSERV EN PLS

**Comment by Achent007** [comment]
Correction, c'est la version paper spigot, j'en attends une compatible avec les plugins, de la 64 à la 68 ça va pas

**Comment by Achent007** [comment]
version 80 corrigé mais les plugins crashent du à un changement d'utilisation d'api de blocs etc

**Comment by Achent007** [comment]
Ce sera pour la 1.14.3 cette merde
